version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"

  ai-service:
    build:
      context: ./ai-service
    ports:
      - "8000:8000"

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
